"""Unified diffs: generate one deterministically, apply one strictly.

ECDAT's fix-it loop hands a template's diff *back to itself* -- the engine
applies the very string a human would apply, rather than re-writing the file
from whatever the template happened to hold in memory. That is the whole point:
a template that produces a diff which does not say what it meant fails
verification instead of shipping.

Two rules make this safe to run unattended:

* **Strict application.** Every context and removed line must match the file
  byte for byte. There is no fuzz factor and no offset search. A patch that
  does not apply exactly is an error, never a best effort -- "roughly applied"
  is how a fix lands on the wrong line.
* **The root is a boundary.** A diff names paths relative to the sandbox root,
  and anything that escapes it -- an absolute path, a ``..`` segment, a symlink
  pointing outward -- is refused before a byte is written. The diff is
  generated by ECDAT today, but it is a data format, and a data format that can
  address the whole filesystem is a liability.

Determinism: no timestamps in the headers (``difflib`` omits them when
``lineterm`` is empty) and a fixed context size, so the same edit always
produces the same bytes.
"""

from __future__ import annotations

import difflib
import re
from dataclasses import dataclass
from pathlib import Path

__all__ = ["PatchError", "apply_unified_diff", "make_unified_diff"]

#: Lines of context either side of a change. Three is what git uses, and it is
#: enough for a reviewer to place the hunk without quoting the whole file.
CONTEXT_LINES = 3

_HUNK_HEADER = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


class PatchError(RuntimeError):
    """A diff could not be parsed, or did not apply exactly."""


@dataclass(frozen=True, slots=True)
class _Hunk:
    old_start: int
    #: ``(kind, text)`` where kind is one of ``" "``, ``"-"``, ``"+"``.
    lines: tuple[tuple[str, str], ...]


def make_unified_diff(relative_path: str, old: str, new: str) -> str:
    """A git-style unified diff turning ``old`` into ``new``.

    ``relative_path`` is relative to the target root, so the diff is portable:
    it carries no sandbox path and applies with ``git apply -p1`` from the
    repository root, which is what makes it PR-ready.
    """
    if old == new:
        return ""
    diff = difflib.unified_diff(
        old.splitlines(),
        new.splitlines(),
        fromfile=f"a/{relative_path}",
        tofile=f"b/{relative_path}",
        lineterm="",
        n=CONTEXT_LINES,
    )
    return "\n".join(diff) + "\n"


def _relative_from_header(header: str) -> str:
    """``+++ b/deploy/nginx.conf`` -> ``deploy/nginx.conf``."""
    path = header.split("\t", 1)[0].strip()
    for prefix in ("a/", "b/"):
        if path.startswith(prefix):
            return path[len(prefix) :]
    return path


def _resolve_inside(root: Path, relative: str) -> Path:
    """The file this hunk addresses, proved to live under ``root``."""
    if not relative or relative == "/dev/null":
        raise PatchError(f"the diff names no usable path: {relative!r}")
    candidate = Path(relative)
    if candidate.is_absolute():
        raise PatchError(f"refusing an absolute path in a diff: {relative!r}")

    root_resolved = root.resolve()
    # resolve() collapses `..` and follows symlinks, so both escape routes are
    # caught by the same containment test.
    resolved = (root / candidate).resolve()
    if resolved != root_resolved and root_resolved not in resolved.parents:
        raise PatchError(
            f"refusing a diff that addresses {relative!r}, which is outside the "
            f"sandbox root {root_resolved}"
        )
    return resolved


def _parse(diff: str) -> list[tuple[str, list[_Hunk]]]:
    """``[(relative path, hunks)]`` in file order."""
    files: list[tuple[str, list[_Hunk]]] = []
    hunks: list[_Hunk] = []
    current: str | None = None
    kinds: list[tuple[str, str]] = []
    old_start = 0
    open_hunk = False

    def close_hunk() -> None:
        nonlocal open_hunk, kinds
        if open_hunk:
            hunks.append(_Hunk(old_start=old_start, lines=tuple(kinds)))
            kinds = []
            open_hunk = False

    def close_file() -> None:
        nonlocal current, hunks
        close_hunk()
        if current is not None:
            files.append((current, hunks))
            hunks = []
            current = None

    for line in diff.splitlines():
        if line.startswith("--- "):
            close_file()
            continue
        if line.startswith("+++ "):
            close_hunk()
            current = _relative_from_header(line[4:])
            continue

        header = _HUNK_HEADER.match(line)
        if header:
            if current is None:
                raise PatchError("a hunk appeared before any file header")
            close_hunk()
            old_start = int(header.group(1))
            open_hunk = True
            continue

        if not open_hunk:
            # Anything outside a hunk (index lines, "diff --git", prose) is not
            # ours to interpret.
            continue
        if line.startswith("\\"):  # "\ No newline at end of file"
            continue
        if line[:1] in (" ", "-", "+"):
            kinds.append((line[0], line[1:]))
        elif line == "":
            # An empty context line: difflib writes " " but some tools strip
            # trailing whitespace on the way through a patch file.
            kinds.append((" ", ""))
        else:
            raise PatchError(f"unrecognised line inside a hunk: {line!r}")

    close_file()
    return files


def _apply_hunks(text: str, hunks: list[_Hunk], relative: str) -> str:
    lines = text.splitlines()
    result: list[str] = []
    cursor = 0

    for hunk in hunks:
        start = max(hunk.old_start - 1, 0)
        if start < cursor:
            raise PatchError(f"overlapping hunks in {relative!r}")
        result.extend(lines[cursor:start])
        cursor = start

        for kind, content in hunk.lines:
            if kind == "+":
                result.append(content)
                continue
            if cursor >= len(lines):
                raise PatchError(
                    f"{relative}: the diff expects a line {cursor + 1} that the "
                    f"file does not have"
                )
            if lines[cursor] != content:
                raise PatchError(
                    f"{relative}:{cursor + 1}: the diff does not apply -- "
                    f"expected {content!r}, found {lines[cursor]!r}"
                )
            if kind == " ":
                result.append(content)
            cursor += 1

    result.extend(lines[cursor:])
    # Preserve whether the file ended with a newline; rewriting that is a
    # spurious change in every diff a reviewer ever reads afterwards.
    return "\n".join(result) + ("\n" if text.endswith("\n") else "")


def apply_unified_diff(root: Path, diff: str) -> None:
    """Apply ``diff`` to the tree under ``root``, or raise :class:`PatchError`.

    Every file is validated and rewritten in turn. There is no rollback: the
    caller applies diffs to a throwaway sandbox copy, so a partial application
    is discarded with the directory rather than repaired.
    """
    parsed = _parse(diff)
    if not parsed:
        raise PatchError("the diff contains no file headers")

    for relative, hunks in parsed:
        path = _resolve_inside(root, relative)
        if not hunks:
            continue
        if not path.is_file():
            raise PatchError(f"the diff patches {relative!r}, which is not a file")
        text = path.read_text(encoding="utf-8")
        path.write_text(_apply_hunks(text, hunks, relative), encoding="utf-8")
