"""What a report reads: the stored CBOM, flattened once.

Every report is a projection of a scan that already happened. Nothing here
scans, scores, or re-derives a band -- the numbers come off the ``ecdat:*``
properties the policy engine and the correlator wrote, so a PDF and the
dashboard cannot disagree about the same scan, and a report issued in March can
be regenerated byte-for-byte from the row that produced it.

This is the Python twin of ``web/src/api/parse.ts``, and for the same reason:
the CBOM's ECDAT content lives in a flat, REPEATING ``properties`` array, and
reading it as a mapping would silently keep one of each.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from core import store
from core.store import UnknownScanError
from core.summary import BAND_NAMES, VerdictSummary, summarise

__all__ = [
    "BAND_NAMES",
    "Artefact",
    "Drift",
    "Occurrence",
    "ScanView",
    "UnknownScanError",
    "load_scan",
]

#: Highest severity first. Report sections are ordered by it.
BAND_ORDER = {band: index for index, band in enumerate(BAND_NAMES)}

#: Views a complete scan collects. A view that is absent was NOT looked at,
#: which is the distinction the coverage statement exists to draw.
ALL_VIEWS = ("declared", "shipped", "observed")


@dataclass(frozen=True, slots=True)
class Occurrence:
    view: str
    locator: str
    scanner: str
    detail: str
    snippet: str | None


@dataclass(frozen=True, slots=True)
class Drift:
    kind: str
    declared: str
    observed: str
    cause: str
    evidence: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class Artefact:
    bom_ref: str
    name: str
    view: str
    band: str
    score: int
    asset_type: str
    usage: str
    endpoint: str | None
    deadline: str | None
    labels: tuple[str, ...]
    fired_rules: tuple[str, ...]
    actions: tuple[str, ...]
    categories: tuple[tuple[str, int], ...]
    quantum_status: str | None
    occurrences: tuple[Occurrence, ...]
    drift: tuple[Drift, ...]
    coverage_views: tuple[str, ...]
    coverage_missing: tuple[str, ...]
    provisional: bool
    provisional_rules: tuple[str, ...]
    deadline_provisional: bool
    fix_template: str | None = None
    fix_verified: bool = False
    fix_reason: str | None = None
    fix_diff: str | None = None

    @property
    def rank(self) -> tuple[int, int, str]:
        """Worst first, ties broken so the order is total and reproducible."""
        return (BAND_ORDER.get(self.band, 99), -self.score, self.name)


@dataclass(frozen=True, slots=True)
class ScanView:
    """One stored scan, as a report needs it."""

    scan: store.Scan
    artefacts: tuple[Artefact, ...]
    summary: VerdictSummary
    system: str
    #: Views present in the document. Anything in ALL_VIEWS and not here was
    #: not collected -- never "collected and clean".
    views_present: tuple[str, ...] = field(default_factory=tuple)

    @property
    def views_missing(self) -> tuple[str, ...]:
        return tuple(v for v in ALL_VIEWS if v not in self.views_present)

    @property
    def drift_total(self) -> int:
        return sum(self.summary.drift_counts.values())

    def worst(self, limit: int) -> list[Artefact]:
        return sorted(self.artefacts, key=lambda a: a.rank)[:limit]

    def by_band(self) -> list[tuple[str, list[Artefact]]]:
        """Populated bands, worst first. Empty bands are omitted here and
        reported as zero in the summary, so a reader sees both."""
        grouped: dict[str, list[Artefact]] = {}
        for artefact in sorted(self.artefacts, key=lambda a: a.rank):
            grouped.setdefault(artefact.band, []).append(artefact)
        return [(band, grouped[band]) for band in BAND_NAMES if band in grouped]

    @property
    def drifted(self) -> list[Artefact]:
        return [a for a in sorted(self.artefacts, key=lambda a: a.rank) if a.drift]

    @property
    def provisional(self) -> list[Artefact]:
        return [
            a for a in sorted(self.artefacts, key=lambda a: a.rank) if a.provisional
        ]


# ---------------------------------------------------------------------------
# Reading the document
# ---------------------------------------------------------------------------


def _all(properties: list[dict[str, str]], name: str) -> list[str]:
    return [p["value"] for p in properties if p.get("name") == name]


def _one(properties: list[dict[str, str]], name: str) -> str | None:
    for prop in properties:
        if prop.get("name") == name:
            return prop["value"]
    return None


def _split(properties: list[dict[str, str]], name: str) -> tuple[str, ...]:
    raw = _one(properties, name)
    if not raw:
        return ()
    return tuple(part.strip() for part in raw.split(",") if part.strip())


def _occurrences(component: dict[str, Any]) -> tuple[Occurrence, ...]:
    properties = component.get("properties", [])
    evidence = (component.get("evidence") or {}).get("occurrences") or []
    found: list[Occurrence] = []
    for raw in _all(properties, "ecdat:occurrence"):
        view, _, rest = raw.partition("|")
        locator, _, rest = rest.partition("|")
        scanner, _, detail = rest.partition("|")
        path = locator.rsplit(":", 1)[0]
        match = next((e for e in evidence if e.get("location") == path), None)
        found.append(
            Occurrence(
                view=view,
                locator=locator,
                scanner=scanner,
                detail=detail,
                snippet=(match or {}).get("additionalContext"),
            )
        )
    return tuple(found)


def _drifts(properties: list[dict[str, str]]) -> tuple[Drift, ...]:
    kinds = _all(properties, "ecdat:drift:kind")
    if not kinds:
        return ()
    declared = _all(properties, "ecdat:drift:declared")
    observed = _all(properties, "ecdat:drift:observed")
    causes = _all(properties, "ecdat:drift:cause")
    evidence = tuple(_all(properties, "ecdat:drift:evidence"))
    return tuple(
        Drift(
            kind=kind,
            declared=declared[index] if index < len(declared) else "",
            observed=observed[index] if index < len(observed) else "",
            cause=causes[index] if index < len(causes) else "",
            evidence=evidence,
        )
        for index, kind in enumerate(kinds)
    )


def _artefact(component: dict[str, Any]) -> Artefact:
    properties: list[dict[str, str]] = component.get("properties", [])
    categories = tuple(
        (entry.split("=", 1)[0], int(entry.split("=", 1)[1] or 0))
        for entry in _all(properties, "ecdat:category_score")
        if "=" in entry
    )
    score = _one(properties, "ecdat:score")
    return Artefact(
        bom_ref=str(component.get("bom-ref", "")),
        name=str(component.get("name", "")),
        view=_one(properties, "ecdat:view") or "declared",
        band=_one(properties, "ecdat:band") or "Low",
        score=int(score) if score and score.isdigit() else 0,
        asset_type=_one(properties, "ecdat:asset_type") or "unknown",
        usage=_one(properties, "ecdat:usage") or "unknown",
        endpoint=_one(properties, "ecdat:param:endpoint"),
        deadline=_one(properties, "ecdat:deadline"),
        labels=_split(properties, "ecdat:labels"),
        fired_rules=_split(properties, "ecdat:fired_rules"),
        actions=tuple(_all(properties, "ecdat:actions")),
        categories=categories,
        quantum_status=_one(properties, "ecdat:quantum_status"),
        occurrences=_occurrences(component),
        drift=_drifts(properties),
        coverage_views=_split(properties, "ecdat:coverage:views"),
        coverage_missing=_split(properties, "ecdat:coverage:missing"),
        provisional=_one(properties, "ecdat:provisional") == "true",
        provisional_rules=tuple(_all(properties, "ecdat:provisional_rule")),
        deadline_provisional=_one(properties, "ecdat:deadline_provisional") == "true",
        fix_template=_one(properties, "ecdat:fix:template"),
        fix_verified=_one(properties, "ecdat:fix:verified") == "true",
        fix_reason=_one(properties, "ecdat:fix:reason"),
        fix_diff=_one(properties, "ecdat:fix:diff"),
    )


def load_scan(scan_id: str) -> ScanView:
    """Read a stored scan into the shape every report renders from."""
    import json

    record = store.get_scan(scan_id)
    if record is None:
        raise UnknownScanError(
            f"no scan with id {scan_id!r} in {store.database_location()}. "
            f"`ecdat scans` lists what is actually there."
        )

    document = json.loads(record.cbom_json)
    artefacts = tuple(_artefact(c) for c in document.get("components", []))
    metadata = (document.get("metadata") or {}).get("component") or {}
    system = str(metadata.get("name") or record.target_system or record.target_ref)

    return ScanView(
        scan=record,
        artefacts=artefacts,
        summary=summarise(document),
        system=system,
        views_present=tuple(
            view for view in ALL_VIEWS if any(a.view == view for a in artefacts)
        ),
    )
